# Assignment - Programming for Data Analysis - Winter 2021




##                                The Numpy.Random Package

#### Fezeka Nzimande GMIT student G00387842


The aim of this project is to explain the overall use of the Python numpy.random package, particularly the use of it’s simple random data functions, permutations functions and distributions functions. The final section delves into the use of seeds in generating pseudorandom numbers. I plan to answer these in a more understandable way by simplifiying the jargon contained in the package for better inderstanding and including illustrations to support my work.

#### Problem Statement:

1. Explain the overall purpose of the package.
2. Explain the use of simple random data and Permurtations functions
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

In [3]:
#import libraries#

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


### 1. Explain the overall purpose of the package.

Numerical Python, well known as NumPy is a specialist package needed for scientific computing with Python. It is close to Python's standard library random but works with NumPy's array. It provides:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


It is a Python library that is efficient in and cleverly overcomes the problem of running slower algorithms on Python by using multidimensional arrays (lists within lists), matrices and functions that operate on arrays[1].
"While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous[5]." There are various ways to create arrays, to demonstrate, I will outline below the single and multi-dimensional array examples.


In [4]:
#single dimensional array#

a = np.array ([1, 2, 3])
print (a)

[1 2 3]


In [5]:
#multi-dimensional array#

a = np.array ([(2, 4, 6), (8, 10, 12)])
print (a)


[[ 2  4  6]
 [ 8 10 12]]


Therefore, although similar to Python lists, NumPy arrays are much more compact and efficient. They may also be refered to as ndarrays. An N-dimensional array is simply an array with any number of dimensions.

### 2. Explain the use of the “Simple random data” and “Permutations” functions.





### REFERENCES
[1] Reitz, Kenneth. "Scientific Applications", The Hitchhiker's Guide to Python. Website: https://docs.python-guide.org/scenarios/scientific/, Accessed 20 Nov. 2021.

[2]Pradhan, Tanvi. "Manipulating Data with Numpy". Website: https://medium.com/analytics-vidhya/manipulating-data-with-numpy-1bb9baaccfbf. Accessed 21 Nov. 2021

[3] VanderPlas, Jake. "Python Data Science Handbook: Essential Tools for Working with Data". Copyright 2017.

[4] SciPy.Org. "Numpy and Scipy Documentation". Website: https://docs.scipy.org/doc/. Accessed 20 Nov. 2021

[5] Numpy.org. "Quickstart and The Absolute Basics for Beginners". Website: https://numpy.org/devdocs/user/absolute_beginners.html Accessed 20 Nov.2021

