# Assignment - Programming for Data Analysis - Winter 2021




##                                The Numpy.Random Package

#### Fezeka Nzimande GMIT student G00387842


The aim of this project is to explain the overall use of the Python numpy.random package, particularly the use of it’s simple random data functions, permutations functions and distributions functions. The final section delves into the use of seeds in generating pseudorandom numbers. I plan to answer these in a more understandable way by simplifiying the jargon contained in the package for better inderstanding and including illustrations to support my work.

#### Problem Statement:

1. Explain the overall purpose of the package.
2. Explain the use of simple random data and Permurtations functions
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

In [3]:
#import libraries#

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


### 1. Explain the overall purpose of the package.

Numerical Python, well known as NumPy is a specialist package needed for scientific computing with Python. It is close to Python's standard library random but works with NumPy's array. It provides:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


It is a Python library that is efficient in and cleverly overcomes the problem of running slower algorithms on Python by using multidimensional arrays (lists within lists), matrices and functions that operate on arrays[1].
"While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous[5]." There are various ways to create arrays, to demonstrate, I will outline below the single and multi-dimensional array examples.


In [4]:
#single dimensional array#

a = np.array ([1, 2, 3])
print (a)

[1 2 3]


In [5]:
#multi-dimensional array#

a = np.array ([(2, 4, 6), (8, 10, 12)])
print (a)


[[ 2  4  6]
 [ 8 10 12]]


Therefore, although similar to Python lists, NumPy arrays are much more compact and efficient. They may also be refered to as ndarrays. An N-dimensional array is simply an array with any number of dimensions.

### 2. Explain the use of the “Simple random data” and “Permutations” functions.

Random in this case does not mean a different elemes each time.. It simply means generating elements in an unpredictable manner. ( The Random module can be split in to 2 sections-- numbers ...) The most simplest example of 
random logic is as below:






In [3]:
from numpy import random
x = random.randint (2500)
print(x)

358


Permutations: The permutation method is used to calculate the number of occurrences when order matters.


Permutation(x) : A random permutation of the sequence, or a range of permuted values.

Shuffle(x): Modifies a sequence in-place by shuffling its elements. This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same[5].


Example below: 

In [7]:
arr = np.arange(35)
>>> np.random.shuffle(arr)
>>> arr #random#


array([23, 28,  2, 19, 21, 14, 13, 20,  6, 12, 29, 34,  7,  9, 26,  3, 27,
        8, 24, 33, 31,  4,  1, 17, 30, 18,  0, 22, 10, 11, 32, 25, 16, 15,
        5])

A simple random sample is a set of n objects in a population of N objects where all possible samples are equally likely to happen[6]. Random number genereation is necessary for processes where objectivity is imperitive for example,a game of russian roulette, lottery, etc. It is also very important for security purpose, generating encryption codes for instance.

The BitGenerators are objects whose purpose is to generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
A generator takes a sequence of random bits from a BitGenerator and turns them into a sequence of numbers following a specific probability distribution (such as Uniform, Normal, or Binomial) within a specified time interval.
 Examples below:

3. Explain the use and purpose of at least five “Distributions” functions.


### REFERENCES

[1] Reitz, Kenneth. "Scientific Applications", The Hitchhiker's Guide to Python. Website: https://docs.python-guide.org/scenarios/scientific/, Accessed 20 Nov. 2021.

[2]Pradhan, Tanvi. "Manipulating Data with Numpy". Website: https://medium.com/analytics-vidhya/manipulating-data-with-numpy-1bb9baaccfbf. Accessed 21 Nov. 2021

[3] VanderPlas, Jake. "Python Data Science Handbook: Essential Tools for Working with Data". Copyright 2017.

[4] SciPy.Org. "Numpy and Scipy Documentation". Website: https://docs.scipy.org/doc/. Accessed 20 Nov. 2021

[5] Numpy.org. "Quickstart and The Absolute Basics for Beginners". Website: https://numpy.org/devdocs/user/absolute_beginners.html Accessed 20 Nov.2021

[6] Simple Random Sample: Definitions and Examples. Website: https://www.statisticshowto.com/probability-and-statistics/statistics-definitions/simple-random-sample/ Accessed 22 Nov. 2021

